user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ShowDashboard.as_view(template_name='user/dashboard.html'), name='dashboard'),
    path('myaction/', MyAction.as_view(), name='my-action'),
]

webPla/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as userViews

from django.contrib.auth import views as authViews

urlpatterns = [
    path('', authViews.LoginView.as_view(template_name='user/login.html'), name='auth'),
    path('profile/', userViews.ShowDashboard.as_view(template_name='user/profile.html'), name='profile'),
    path('exit/', authViews.LogoutView.as_view(template_name='user/exit.html'), name='exit'),
    path('admin/', admin.site.urls, name='admin'),
    path('dashboard/', userViews.ShowDashboard.as_view(template_name='user/dashboard.html'), name='dashboard'),
    # path('forms/', userViews.ShowDashboard._form_view, name='user'),
    # path('dashboardC/', userViews.ShowDashboardC.as_view(template_name='user/dashboard.html'), name='dashboardC'),
    path('password/', userViews.change_password, name='change_password'),
    path('enter/', userViews.my_redirect, name='my_redirect'),

]

user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Test(models.Model):
    town_name = models.CharField(unique=True, max_length=20)
    class Meta:
        ordering = ["town_name"]
    def __str__(self):
        return self.town_name
class Town(models.Model):
    town_name = models.CharField(unique=True, max_length=20)
    class Meta:
        ordering = ["town_name"]
    def __str__(self):
        return self.town_name
class Street(models.Model):
    street_name = models.CharField(unique=True, max_length=50)
    town = models.ForeignKey(Town, on_delete = models.CASCADE, to_field = "town_name", related_name='+')
    class Meta:
        ordering = ["street_name"]
    def __str__(self):
        return self.street_name
class House(models.Model):
    number = models.CharField(unique=True, max_length=5)
    street = models.ForeignKey(Street, on_delete = models.CASCADE, to_field = "street_name", related_name='+')
    class Meta:
        ordering = ["number"]
    def __str__(self):
        return self.number

class Privelege(models.Model):
    privelege = models.CharField(max_length=20, verbose_name='Пільга')
    limit = models.IntegerField(verbose_name='Ліміт пільг.споживання')
    limit_price = models.FloatField(verbose_name = "пільгова ціна")
    price = models.FloatField(verbose_name = "ціна")
    class Meta:
        ordering = ["id"]
    def __str__(self):
        template = '{0.privelege}'
        return template.format(self)

class Private_abonent(models.Model):
    account = models.OneToOneField(User, on_delete=models.CASCADE, to_field = "username", primary_key=True, verbose_name='О/Р')
    first_name = models.CharField(max_length=20, verbose_name='Ім\'я')
    last_name = models.CharField(max_length=20, verbose_name='Побатькові')
    sur_name = models.CharField(max_length=30, verbose_name='Прізвище')
    house_number = models.ForeignKey(House, on_delete = models.CASCADE, related_name='+', to_field = "number", verbose_name='Будинок')
    apartament = models.IntegerField(null=True, default=0, verbose_name='Квартира')
    meter_sn = models.CharField(max_length=20, null=True, blank = True, verbose_name='Лічильник №:')
    phone_num = models.CharField(max_length=13, null=True, blank = True, verbose_name='Ном.телефону')
    email = models.EmailField(max_length=100, null=True, blank = True, verbose_name='Ел. поштова скринька')
    tariff = models.ForeignKey(Privelege, on_delete=models.CASCADE, default=1, verbose_name='Тариф')
    class Meta:
        ordering = ["account"]
    def __str__(self):
        template = '{0.account} {0.sur_name} {0.house_number.street} {0.house_number.number}'
        return template.format(self)


class Comercial(models.Model):
    account = models.ForeignKey(User, on_delete=models.CASCADE)
    contract=models.CharField(max_length=100, verbose_name='О/Р', primary_key=True)
    name = models.CharField(max_length=100, verbose_name='Споживач')
    ipn = models.CharField(max_length=20, verbose_name='ІПН', null=True)
    meter_sn = models.CharField(max_length=20, null=True, blank = True, verbose_name='Лічильник №:')
    phone_num = models.CharField(max_length=13, null=True, blank = True, verbose_name='Ном.телефону')
    email = models.EmailField(max_length=100, null=True, blank = True, verbose_name='Ел. поштова скринька')
    class Meta:
        ordering = ["account"]
    def __str__(self):
        template = '{0.account} {0.contract} {0.name} {0.ipn} {0.meter_sn} {0.phone_num} {0.email}'
        return template.format(self)
        # return str(self.account), str(self.sur_name), str(self.house_number.street), str(self.house_number.number)

class balans(models.Model):
    account = models.ForeignKey(User, on_delete=models.CASCADE, to_field = "username")
    saldo = models.FloatField(verbose_name = "saldo", default=0)
    comment = models.CharField(max_length=100, null=True)
    date = models.DateField(auto_now=False, auto_now_add=False)
    class Meta:
        ordering = ["-date"]
    def __str__(self):
        template = '{0.account} {0.saldo} {0.date} {0.comment}'
        return template.format(self)

class spozHistory(models.Model):
    account = models.ForeignKey(User, on_delete=models.CASCADE, to_field = "username")
    date = models.DateField(verbose_name = "місяць", auto_now=False, auto_now_add=False)
    pokaz1 = models.FloatField(verbose_name = "поч.показник", default=0)
    pokaz2 = models.FloatField(verbose_name = "кін.показник", default=0)
    different = models.FloatField(verbose_name = "спожито кВт", default=0)
    uah = models.FloatField(verbose_name = "грн", default=0)

    class Meta:
        ordering = ["-date"]
    def __str__(self):
        template = '{0.account} {0.date} {0.pokaz1} {0.pokaz2} {0.different} {0.uah}'
        return template.format(self)
        # return self.account, self.saldo, self.date, self.comment
class meterDataPrivate(models.Model):
    account = models.ForeignKey(Private_abonent, on_delete=models.CASCADE)
    pokazT0 = models.FloatField(verbose_name = "показник", default='0.0')
    pokazT1 = models.FloatField(verbose_name = "показник", default='0.0')
    pokazT2 = models.FloatField(verbose_name = "показник", default='0.0')
    pokazT3 = models.FloatField(verbose_name = "показник", default='0.0')
    date = models.DateField(verbose_name = "Дата", auto_now=False, auto_now_add=False)
    comment = models.CharField(max_length=100, null=True, verbose_name='Джерело')
    class Meta:
        ordering = ["-date"]
    def __str__(self):
        template = '{0.date} {0.pokaz}'
        return template.format(self)
        # return self.account, self.saldo, self.date, self.comment

class gadget_hw(models.Model):
    contract = models.ForeignKey(Comercial, on_delete=models.CASCADE, to_field = "contract")
    model = models.CharField(max_length=50, null=True)
    class Meta:
        ordering = ["id"]
    def __str__(self):
        template = '{0.id} {0.model}'
        return template.format(self)

class gadget_HW_meter(models.Model):
    kWh = models.FloatField(verbose_name = "кВт", default=0)
    kVArh_p = models.FloatField(verbose_name = "кВар поз.", default=0)
    kVArh_n = models.FloatField(verbose_name = "кВар нег.", default=0)
    kVAh = models.FloatField(verbose_name = "кВА", default=0)
    cur_sum_V = models.FloatField(verbose_name = "В", default=0)
    cur_L1_V = models.FloatField(verbose_name = "В Ф1", default=0)
    cur_L2_V = models.FloatField(verbose_name = "В Ф2", default=0)
    cur_L3_V = models.FloatField(verbose_name = "В Ф3", default=0)
    cur_F = models.FloatField(verbose_name = "Частота", default=0)
    meterDate = models.BigIntegerField(verbose_name = "Дата", default=0)
    gadget_HW_id = models.ForeignKey(gadget_hw, on_delete=models.CASCADE, verbose_name = "№ пристрою")
    class Meta:
        ordering = ["meterDate"]
    def __str__(self):
        template = '{0.kWh} {0.kVArh_p} {0.kVArh_n} {0.kVAh} {0.cur_sum_V} {0.cur_L1_V} {0.cur_L2_V} {0.cur_L3_V} {0.cur_F} {0.meterDate}'
        return template.format(self)

class gadget_HW_meter_max_dem_h(models.Model):
    kW = models.FloatField(verbose_name = "макс.кВт", default=0)
    meterDate = models.BigIntegerField(verbose_name = "Дата", default=0)
    gadget_HW_id = models.ForeignKey(gadget_hw, on_delete=models.CASCADE, verbose_name = "№ пристрою")
    class Meta:
        ordering = ["meterDate"]
    def __str__(self):
        template = '{0.kW} {0.meterDate}'
        return template.format(self)

user/forms.py
from django.forms import ModelForm, DateInput, HiddenInput, CharField
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import meterDataPrivate, Private_abonent

class UserMeterDate(ModelForm):

    class Meta:
        model = meterDataPrivate
        fields = ['account', 'pokazT0', 'date', 'comment']
        widgets = {'account': HiddenInput(),
                   'date': HiddenInput(),
                   'comment': HiddenInput()}
        help_text = {'pokazT0':'Показник не може відрізнятись більше ніж на десять одиниць',}

class ChangeEmailForm(ModelForm):
    email = forms.EmailField(label='Новый адрес электронной почты', max_length=254,
                             widget=forms.EmailInput(attrs={'autofocus': ''}),
                             error_messages={'unique': 'Данный адрес электронной почты уже используется'})

    class Meta:
        model = Private_abonent
        fields = ['email']

    def send_vcode(self, request, user):
        Vcode(request).send(user, 'change_email', {
            'email': self.cleaned_data['email'],
        })


# class ContactForm(form):
#     name = forms.CharField(max_length=30)
#     email = forms.EmailField(max_length=254)
#     message = forms.CharField(
#         max_length=2000,
#         widget=forms.Textarea(),
#         help_text='Write here your message!'
#     )
#     source = forms.CharField(
#         max_length=50,
#         widget=forms.HiddenInput()
#     )
#
#     def clean(self):
#         cleaned_data = super(ContactForm, self).clean()
#         name = cleaned_data.get('name')
#         email = cleaned_data.get('email')
#         message = cleaned_data.get('message')
#         if not name and not email and not message:
#             raise forms.ValidationError('You have to write something!')

user/templates/user/change_email.html
|{% extends 'user/main.html'%}

{% load crispy_forms_tags %}

{% block main_section %}
<h1>Додати електронну адресу</h1>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-outline-warning">Підтвердити</button>
</form>
{% endblock main_section %}

user/templates/user/change_password.html
{% extends 'user/main.html'%}

{% load crispy_forms_tags %}

{% block main_section %}
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-outline-warning">Підтвердити</button>
</form>
{% endblock main_section %}

user/templates/user/dashboard.html
{% extends 'user/dashboardTemp.html'%}
{% load static %}
{% load crispy_forms_tags %}
{% load user_tags %}
{% load widget_tweaks %}
<!-- {% if perms.user.add_street %}
    <h1>Good Work</h1>
{% else %}
    <h1>Fail</h1>
{% endif %} -->

<!-- {% if request.user|has_group:"abon" %}
  <h1>Good Work</h1>
{% else %}
    <h1>Fail</h1>
{% endif %} -->

{% block main_section %}
  {% if request.user|has_group:"abon" %}

    <div class="row">
      <div class="col-md-auto">
        <div class="form-section">
          {% for i in abonent %}
            <h5>{{ i.sur_name }} {{ i.first_name }} {{ i.last_name }}</h5>
            <h5>вул.{% for a in adress %}{{ a.street }}  буд.{{ a.number }}{% endfor %} кв:{{ i.apartament }}</h5>
          {% endfor %}
          <h5>Особовий рахунок: {{usersid}}</h5>
        </div>
      </div>
      <div class="col-md-auto">
        <div class="form-section">
          <h4>Тариф:</h4>
          <p></p>
          <h5>перших 100кВт/год - 0,9грн</h5>
          <h5>понад 100кВт/год - 1,68грн</h5>
        </div>
      </div>
      <div class="col-md-auto">
        <div class="form-section">
          <h4>Останній зафіксований показник:</h4>
          <p></p>
          {% for i in lastPokaz %}
            <h5>{{i.pokazT0}} кВт/год | {{date}}</h5>
          {% endfor %}
          <h3>Баланс: {{balans_sum.saldo__sum|floatformat:"3"}} грн</h3>
        </div>
      </div>
      {% if shadowForm %}
      <div class="col-md-auto">
        <!-- <p> Подача показників </p> -->
        <form method="post">
          {% csrf_token %}
          {{ form}}
          <button type="submit" class="btn btn-primary">Підтвердити</button>
        </form>
      </div>
      {% endif %}
    </div>
  {% endif %}
  {% if request.user|has_group:"comercial" %}

  {% endif %}
  {% if request.user|has_group:"admin" %}
    <div class="row">
      <div class="col-md-auto">
        <div class="form-section">
          <h4>Середнє споживання в день: {{dayAverage|floatformat:"2"}}</h4>
          <h4>Прогноз споживання в місяць: {{Forecast|floatformat:"2"}}</h4>
        </div>
      </div>
      <div class="col-md-auto">
        <div class="form-section">
            <h4>Спожито в поточному місяці:  {{count|floatformat:"2"}}</h4>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock main_section %}
{% block charts %}
  {% if request.user|has_group:"abon" %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js" type="text/javascript"></script>

    <script type="text/javascript">
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
      type: 'line',
      data: {
            labels: ['Січ', 'Лют', 'Бер', 'Кві', 'Тра', 'Чер', 'Лип', 'Сер', 'Вер', 'Жов', 'Лис', 'Гру', 'Січ'],
            datasets: [{
              label: '2017',
              fill: false,
              borderColor: "rgb(255, 97, 97)",
              backgroundColor: "rgb(255, 97, 97)",
              pointStrokeColor: "#fff",
              pointHighlightFill: "#fff",
              pointHighlightStroke: "rgba(220,220,220,1)",
              data: [0, 0, 0, 0, 0, {% for i in history reversed %}
                                      {{ i.different|floatformat:"0" }},
                                    {% endfor %}],
              yAxisID: 'y-axis-1',
            }, {
              label: '2018',
              fill: false,
              borderColor: "rgb(64, 44, 245)",
              backgroundColor: "rgb(64, 44, 245)",
              pointStrokeColor: "#fff",
              pointHighlightFill: "#fff",
              pointHighlightStroke: "rgba(220,220,220,1)",
              data: [{% for i in history reversed %}
                        {% if forloop.counter > 7 %}
                          {{ i.different|floatformat:"0" }},
                        {% endif %}
                    {% endfor %}],
              yAxisID: 'y-axis-2'
            }]

      },
      options: {responsive: true,
                hoverMode: 'index',
                stacked: false,
                title: {
                  display: true,
                  text: 'Графік споживання'
                },
                scales: {
                  yAxes: [{
                    type: 'linear', // only linear but allow scale type registration. This allows extensions to exist solely for log scale for instance
                    display: true,
                    position: 'left',
                    id: 'y-axis-1',
                  }, {
                    type: 'linear', // only linear but allow scale type registration. This allows extensions to exist solely for log scale for instance
                    display: true,
                    position: 'right',
                    id: 'y-axis-2',

                    // grid line settings
                    gridLines: {
                      drawOnChartArea: false, // only want the grid lines for one axis to show up
                    },
                  }],
                }}
    });
    </script>
  {% endif %}
  {% if request.user|has_group:"comercial" %}

  {% endif %}
  {% if request.user|has_group:"admin" %}

    <script type="text/javascript" src="../static/user/script/moment.min.js">></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">
    var ctx = document.getElementById('myChart').getContext('2d');
    ctx.height = 500;
    var nowDate = new Date()
    var chart = new Chart(ctx, {
      type: 'bar',
      data: {
            labels: [{% for x, y, z in kwhM %}
                      "{{ z|truncatewords:2 }}",
                    {% endfor %}],
            datasets: [{
              label: 'Споживання в годину',
              fill: false,
              borderColor: "rgb(64, 44, 245)",
              backgroundColor: "rgb(64, 44, 245)",
              // pointStrokeColor: "#fff",
              // pointHighlightFill: "#fff",
              pointHighlightStroke: "rgba(220,220,220,1)",
              borderWidth: 2,
              radius: 0,
              data: [{% for x, y, z in kwhM %}
                      {{ x|floatformat:"0" }},
                    {% endfor %}],
              yAxisID: 'y-axis-1'
            }]

      },
      options: {
                events: ["click"],
                responsive: false,
                hoverMode: 'index',
                stacked: false,
                title: {
                  display: true,
                  text: 'Графік споживання'
                },
                scales: {
                  xAxes: [{
                    type: "time",
                    time: {
                      unit: 'hour',
                      unitStepSize: 24,
                      round: 'hour',
                      tooltipFormat: "D-MM-YY h:mm:ss a",
                      displayFormats: {
                        hour: 'D-MM-YY'
                      }
                    }
                  }],
                  yAxes: [{
                    type: 'linear', // only linear but allow scale type registration. This allows extensions to exist solely for log scale for instance
                    display: true,
                    position: 'left',
                    id: 'y-axis-1',
                  }],
                }}
    });
    </script>
  {% endif %}
{% endblock charts%}
{% block content %}
  {% if request.user|has_group:"abon" %}
    <div class="row">
      <div class="col-md-12">
        <canvas id="myChart" height="25%" width="100%" class="chartjs-render-monitor" style="display: block;"></canvas>
      </div>
    </div>
  {% endif %}
  {% if request.user|has_group:"comercial" %}

  {% endif %}
  {% if request.user|has_group:"admin" %}
    <div class="row">
      <div class="col-md-12">
        <canvas id="myChart" class="chartjs-render-monitor" style="height:40vh; width:100%"></canvas>
      </div>
    </div>
  {% endif %}
{% endblock content %}
{% block balans_section %}
  {% if request.user|has_group:"abon" %}
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-auto col-xl-auto">
        <div class="span3">
          <table class="table table-striped">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Дата</th>
                <th scope="col">Поч.показник</th>
                <th scope="col">Кін.показник</th>
                <th scope="col">кВт</th>
                <th scope="col">ГРН</th>
              </tr>
            </thead>
            <tbody>
              {% for i in history %}
              <tr>
                <td>{{i.date|date:'M.y'}}</td>
                <td>{{i.pokaz1}}</td>
                <td>{{i.pokaz2}}</td>
                <td>{{i.different|floatformat:"3"}}</td>
                <td>{{i.uah|floatformat:"3"}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-auto col-xl-auto">
        <div class="span3">
          <table class="table table-striped">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Баланс</th>
                <th scope="col">Дата</th>
                <th scope="col">Коментар</th>
              </tr>
            </thead>
            <tbody>
              {% for i in balans %}
              <tr>
                <td>{{i.saldo|floatformat:"3"}}</td>
                {% if i.comment == 'Нарахування' %}
                  <td>{{i.date|date:'F'}}</td>
                {% endif %}
                {% if i.comment != 'Нарахування' %}
                  <td>{{i.date}}</td>
                {% endif %}
                <td>{{i.comment}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  {% endif %}

  {% if request.user|has_group:"comercial" %}
  {% endif %}

  {% if request.user|has_group:"admin" %}

  {% endif %}
{% endblock balans_section %}

user/templates/user/dashboardC.html
{% extends 'user/dashboardTemp.html'%}
{% load user_tags %}
<!-- {% if perms.user.view_street %}
    <h1>Good Work</h1>
{% else %}
    <h1>Fail</h1>
{% endif %} -->

<!-- {% if request.user|has_group:"abon" %}
  <h1>Good Work</h1>
{% else %}
    <h1>Fail</h1>
{% endif %} -->

{% block main_section %}
  {% if request.user|has_group:"abon" %}
    <div class="row">
      <div class="col-md-auto">
        <div class="form-section">
          <!-- {% for i in abonent %}
          <h5>{{ i.sur_name }} {{ i.first_name }} {{ i.last_name }}</h5>
          <h5>вул.{% for a in adress %}{{ a.street }}  буд.{{ a.number }}{% endfor %} кв:{{ i.apartament }}</h5>
          {% endfor %} -->
          <h5>Особовий рахунок: {{usersid}}</h5>
        </div>
      </div>
      <div class="col-md-auto">
        <div class="form-section">
          <h4>Тариф:</h4>
          <p></p>
          <h5>перших 100кВт/год - 0,9грн</h5>
          <h5>понад 100кВт/год - 1,68грн</h5>
        </div>
      </div>
      <div class="col-md-auto">
        <div class="form-section">
          <h4>Останній зафіксований показник:</h4>
          <p></p>
          <h5>356,26 кВт/год</h5>
          <h3>Баланс: {{balans_sum.saldo__sum|floatformat:"3"}} грн</h3>

        </div>
      </div>
    </div>
  {% endif %}
  {% if request.user|has_group:"comercial" %}

  {% endif %}
  {% if request.user|has_group:"admin" %}

  {% endif %}
{% endblock main_section %}
{% block charts %}
  {% if request.user|has_group:"abon" %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
      type: 'line',
      data: {
            labels: ['Січ', 'Лют', 'Бер', 'Кві', 'Тра', 'Чер', 'Лип', 'Сер', 'Вер', 'Жов', 'Лис', 'Гру', 'Січ'],
            datasets: [{
              label: '2017',
              fill: false,
              borderColor: "rgb(255, 97, 97)",
              backgroundColor: "rgb(255, 97, 97)",
              pointStrokeColor: "#fff",
              pointHighlightFill: "#fff",
              pointHighlightStroke: "rgba(220,220,220,1)",
              data: [0, 0, 0, 0, 0, {% for i in history reversed %}
                                      {{ i.different|floatformat:"0" }},
                                    {% endfor %}],
              yAxisID: 'y-axis-1',
            }, {
              label: '2018',
              fill: false,
              borderColor: "rgb(64, 44, 245)",
              backgroundColor: "rgb(64, 44, 245)",
              pointStrokeColor: "#fff",
              pointHighlightFill: "#fff",
              pointHighlightStroke: "rgba(220,220,220,1)",
              data: [{% for i in history reversed %}
                        {% if forloop.counter > 7 %}
                          {{ i.different|floatformat:"0" }},
                        {% endif %}
                    {% endfor %}],
              yAxisID: 'y-axis-2'
            }]

      },
      options: {responsive: true,
                hoverMode: 'index',
                stacked: false,
                title: {
                  display: true,
                  text: 'Графік споживання'
                },
                scales: {
                  yAxes: [{
                    type: 'linear', // only linear but allow scale type registration. This allows extensions to exist solely for log scale for instance
                    display: true,
                    position: 'left',
                    id: 'y-axis-1',
                  }, {
                    type: 'linear', // only linear but allow scale type registration. This allows extensions to exist solely for log scale for instance
                    display: true,
                    position: 'right',
                    id: 'y-axis-2',

                    // grid line settings
                    gridLines: {
                      drawOnChartArea: false, // only want the grid lines for one axis to show up
                    },
                  }],
                }}
    });
    </script>
  {% endif %}
  {% if request.user|has_group:"comercial" %}

  {% endif %}
  {% if request.user|has_group:"admin" %}

  {% endif %}
{% endblock charts%}
{% block content %}
  {% if request.user|has_group:"abon" %}
    <div class="row">
      <div class="col-md-12">
        <canvas id="myChart" height="25%" width="100%" class="chartjs-render-monitor" style="display: block;"></canvas>
      </div>
    </div>
  {% endif %}
  {% if request.user|has_group:"comercial" %}

  {% endif %}
{% endblock content %}
{% block balans_section %}
  {% if request.user|has_group:"abon" %}
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-auto col-xl-auto">
        <div class="span3">
          <table class="table table-striped">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Дата</th>
                <th scope="col">Поч.показник</th>
                <th scope="col">Кін.показник</th>
                <th scope="col">кВт</th>
                <th scope="col">ГРН</th>
              </tr>
            </thead>
            <tbody>
              {% for i in history %}
              <tr>
                <td>{{i.date|date:'M.y'}}</td>
                <td>{{i.pokaz1}}</td>
                <td>{{i.pokaz2}}</td>
                <td>{{i.different|floatformat:"3"}}</td>
                <td>{{i.uah|floatformat:"3"}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-auto col-xl-auto">
        <div class="span3">
          <table class="table table-striped">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Баланс</th>
                <th scope="col">Дата</th>
                <th scope="col">Коментар</th>
              </tr>
            </thead>
            <tbody>
              {% for i in balans %}
              <tr>
                <td>{{i.saldo|floatformat:"3"}}</td>
                {% if i.comment == 'Нарахування' %}
                  <td>{{i.date|date:'F'}}</td>
                {% endif %}
                {% if i.comment != 'Нарахування' %}
                  <td>{{i.date}}</td>
                {% endif %}
                <td>{{i.comment}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  {% endif %}
  {% if request.user|has_group:"comercial" %}

  {% endif %}
  {% if request.user|has_group:"admin" %}

  {% endif %}
{% endblock balans_section %}

user/templates/user/exit.html
{% extends 'user/main.html'%}
{% block main_section %}
  <div class="form-section">
    <h2>Ви успішно покинули особистий кабінет!</h2>
    <a href="{% url 'auth' %}">Зайти в особистий кабінет</a>
  </div>
{% endblock main_section %}

user/templates/user/profile.html
|{% extends 'user/main.html'%}

{% load crispy_forms_tags %}

{% block main_section %}




{% endblock main_section %}